name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        run: git push https://ushreyas014:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ushreyas014/github-assistant-api main --force
